version: "3.8"

services:
  app:
    build: .
    container_name: upload-file-app
    depends_on:
      - minio-setup
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/datalake
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: datalake1234
      MINIO_URL: http://minio-file-service:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      MINIO_BUCKET_NAME: first-bucket
    ports:
      - "8080:8080"
    # restart: unless-stopped
  minio-file-service:
    image: quay.io/minio/minio:latest
    container_name: minio-file-service
    ports:
      - "9000:9000"
      - "9080:9080"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9080"

  minio-setup:
    image: minio/mc
    depends_on:
      - minio-file-service
    entrypoint: |
      /bin/sh -c '
        set -e
        until mc alias set minio http://minio-file-service:9000 admin admin123 >/dev/null 2>&1; do
          sleep 2
        done
        mc mb -p minio/first-bucket || true
      '

  postgres:
    image: postgres:latest
    container_name: DataLakeDK
    environment:
      POSTGRES_DB: datalake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: datalake1234
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-data:
